services:
  client:
    build: ./client
    network_mode: "host"
    ports:
      - "4000:4000"
  server:
    build: ./server
    network_mode: "host"
    ports:
      - "5000:5000"
  proxy:
    build: ./proxy
    network_mode: "host"
    ports:
      - "443:443"
      - "80:80"